# Temas vistos el 9 de enero del 2022
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/danielroa98/Postgrad-ML/blob/main/Module-2/09_Jan_2023_lec_01_M2G6P_DRG.ipynb)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Para gráficas grandes
plt.rcParams['figure.figsize'] = (14,10)

In [4]:
a = 5.5
print(f"{a} es de tipo {type(a)}")

a = complex(5.5)
print(f"{a} es de tipo {type(a)}")

5.5 es de tipo <class 'float'>
(5.5+0j) es de tipo <class 'complex'>


In [7]:
# Creación manual de un vector
## Se añade un dtype para indicar el tipo de dato
x = np.array([3.4, 1.4, 0.5, 10.4, 0.0], dtype=float)
print(x)

# Creación de un vector de 0 a 5 con incrementos de 1
## dtype indica el tipo de dato que queremos
x = np.arange(0, 5, dtype=float)
print(x)

x = np.ones(5, dtype=int)
print(x)

x = np.zeros(5, dtype=int)
print(x)

x = np.linspace(0, 10, 5)
print(x)

# Creación de un vector columna
## Realmente es una matriz de 3x1
x_col = np.array([
    [0],
    [1],
    [2]
])
print(x_col)

# Creación de un vector fila
x_row = np.array([0, 1, 2])
print(x_row)

# Transposing a column
print(x_col.T)

[ 3.4  1.4  0.5 10.4  0. ]
[0. 1. 2. 3. 4.]
[1 1 1 1 1]
[0 0 0 0 0]
[ 0.   2.5  5.   7.5 10. ]
[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]]


In [8]:
%matplotlib inline

### TODO: complete notes

## Ejercicios

1) Calcula el valor promedio de un vector arbitrario usando el producto punto

In [10]:
x = np.array([1,2,3,4,5])

print((x @ np.ones(len(x))) / (len(x)))

3.0


2) Calcula el valor presente de una serie de flujos anuales de $100 por 15 años, suponiendo una tasa anual constante del 8% (anualidad vencida).