# Temas vistos el 12 de diciembre del 2022
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/danielroa98/Postgrad-ML/blob/main/Module-1/12_Dec_2022_lec_10_M1G6P_DRG.ipynb)

### Library imports

In [1]:
import pandas as pd, numpy as np

## Numpy's functionalities
Continuation of the lecture taken on [December 7, 2022](./07_Dec_2022_lec_09_M1G6P_DRG.ipynb).

In [2]:
arr = np.arange(30).reshape(10,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

Se toma el sexto renglón y se imprime al revés.

In [3]:
arr[5][::-1]

array([17, 16, 15])

Imprime al revés todo el array.

In [4]:
arr[::-1]

array([[27, 28, 29],
       [24, 25, 26],
       [21, 22, 23],
       [18, 19, 20],
       [15, 16, 17],
       [12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

#### _Broadcasting_ es la forma en que Numpy manipula arrays de dimensiones diferentes.
Para 'A', 'B', dos dimensiones son compatibles cuando:
1. Son iguales
2. Una dimensión es igual a _1_.

In [5]:
A = np.arange(25).reshape(5,5)
B = np.arange(5).reshape(1,5)

print(f"{A}\n\n{B}")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[0 1 2 3 4]]


In [6]:
A*B

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76],
       [ 0, 21, 44, 69, 96]])

In [7]:
A+B

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18],
       [15, 17, 19, 21, 23],
       [20, 22, 24, 26, 28]])

`np.zeros()` --> Nos regresa un arreglo solamente de 0s.

In [8]:
np.zeros(shape=10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

`np.ones()` --> Arreglo únicamente de 1s.

In [10]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
arr1 = np.arange(11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr1.sum()

55

In [13]:
arr1.min()

0

In [14]:
arr1.max()

10

In [15]:
arr1.mean()

5.0

In [16]:
arr1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

Generación de números aleatorios

In [17]:
from numpy.random import seed, randint
seed(42)

a2 = randint(5,10,size=(5,10))
a2

array([[8, 9, 7, 9, 9, 6, 7, 7, 7, 9],
       [8, 7, 9, 6, 8, 6, 8, 9, 5, 8],
       [6, 9, 8, 5, 5, 7, 7, 6, 8, 8],
       [7, 8, 8, 5, 7, 9, 7, 9, 5, 6],
       [8, 5, 8, 6, 6, 5, 6, 9, 6, 8]])

Calcular la media por _renglones_ (hacia abajo).

In [18]:
a2.mean(axis=0)

array([7.4, 7.6, 8. , 6.2, 7. , 6.6, 7. , 8. , 6.2, 7.8])

Para calcular la media por _columnas_.

In [19]:
a2.mean(axis=1)

array([7.8, 7.4, 6.9, 7.1, 6.7])

In [20]:
np.unique(a2)

array([5, 6, 7, 8, 9])

Cuando el parámetro `return_index = True`, regresa una tupla con el valor y la posición dentro de larrelgo donde se da la primera ocurrencia de cada valor.

In [21]:
np.unique(a2, return_index=True)

(array([5, 6, 7, 8, 9]), array([18,  5,  2,  0,  1]))

In [22]:
x = np.array(['o','p','a','b','h','o','p'])
u, indices = np.unique(x, return_index=True)

u

array(['a', 'b', 'h', 'o', 'p'], dtype='<U1')

In [23]:
indices

array([2, 3, 4, 0, 1])

`np.where()` --> regresa los indices, no los elementos

- Se pueden usar operaciones lógicas.

In [24]:
a3 = np.array([-1,0,1,-2,1,3,-4])
np.where(a3 > 0)

(array([2, 4, 5]),)

In [25]:
indicesw = np.where(a3 > 0)
a3[indicesw]

array([1, 1, 3])

In [26]:
A = np.array([
    [1,2,3],
    [9,3,2]
])
A

array([[1, 2, 3],
       [9, 3, 2]])

También se puede crear como matrix

- El tipo de dato es diferente al de `array`.

In [27]:
B = np.matrix([
    [1,2,3],
    [9,3,2]
])
B

matrix([[1, 2, 3],
        [9, 3, 2]])

In [28]:
B.T

matrix([[1, 9],
        [2, 3],
        [3, 2]])

#### Multiplicación matricial

Se utiliza `@` para llevar a cabo la multiplicación.

In [29]:
# A@B
## Al no tener las mismas dimensiones, va a marcar un error y no se va a poder correr

In [30]:
A@B.T

matrix([[14, 21],
        [21, 94]])

In [31]:
# Dot product o producto punto
np.dot(A,B.T)

matrix([[14, 21],
        [21, 94]])

In [32]:
C = np.matrix([
    [1,2,3],
    [1,2,3]
])
C

matrix([[1, 2, 3],
        [1, 2, 3]])

In [33]:
unos = np.array([[1,1,1]])
unos_c = unos.reshape(3,1)

unos_c

array([[1],
       [1],
       [1]])

In [34]:
np.dot(C, unos_c)

matrix([[6],
        [6]])

In [35]:
C@unos_c

matrix([[6],
        [6]])

### `numpy.linalg()`

In [36]:
from numpy import linalg

In [37]:
D = np.array([2,1,2,4]).reshape(2,2)
D

array([[2, 1],
       [2, 4]])

In [38]:
linalg.inv(D)

array([[ 0.66666667, -0.16666667],
       [-0.33333333,  0.33333333]])

In [39]:
D@linalg.inv(D)

array([[1., 0.],
       [0., 1.]])

In [40]:
np.dot(D, linalg.inv(D))

array([[1., 0.],
       [0., 1.]])

Para sacar la matriz de identidad de $n*n$

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Dentro de la librería de `linalg` existe la función `eig()`

- Esta obtiene los eigenvalores() y los eigenvectores.

In [42]:
linalg.eig(D)
## El primer arreglo da los eigenvalores y el segundo son los eigenvectores.

(array([1.26794919, 4.73205081]),
 array([[-0.80689822, -0.34372377],
        [ 0.59069049, -0.9390708 ]]))

Si tenemos para una matriz _A_, vector _v_ y escalar $k ≠ 0$ tales que $AV = Kv$, entonces _v_ eigenvector de A asociado al eigenvalor k

In [43]:
linalg.eig(D)[0]

array([1.26794919, 4.73205081])

In [44]:
linalg.eig(D)[1]

array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]])

In [46]:
D@np.array([-0.80689822, 0.59069049]).reshape(2,1)

array([[-1.02310595],
       [ 0.74896552]])

In [47]:
np.array([-0.80689822, 0.59069049]).reshape(2,1)*1.26794919

array([[-1.02310594],
       [ 0.74896553]])

In [49]:
np.array([-0.80689822, 0.59069049]).reshape(2,1)*linalg.eig(D)[0][0]

array([[-1.02310595],
       [ 0.74896553]])

In [50]:
D@np.array([-0.34372377, -0.9390708]).reshape(2,1)

array([[-1.62651834],
       [-4.44373074]])

In [51]:
np.array([-0.34372377, -0.9390708]).reshape(2,1)*4.73205081

array([[-1.62651834],
       [-4.44373074]])

In [52]:
k, v = linalg.eig(np.diag((1,2,3)))

In [53]:
k

array([1., 2., 3.])

In [54]:
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
D = np.diag((1,2,3))
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [56]:
D@v

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])